name: generate
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: "3.19.4"
      - name: Install go gRPC and protobuf packages
        run: |
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.6.0"
      - name: Generate
        run: |
          find noted -name "*.go" -type f -delete
          find noted -name "*.py" -type f -delete
          buf generate
      - name: Add generated code
        run: git add -f .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "ci: generate protobuf code"
          commit_user_name: Protobot
          status_options: ""
